name: Push to master
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ARTIFACTORY_DEPLOY_USER }}
        password: ${{ secrets.ARTIFACTORY_DEPLOY_PASSWORD }}
        registry: artifactory.rtr.cloud
        repository: docker/vault-auto-config
        tags: latest
